apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-au0y
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-au0y
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-au0y
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-au0y
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-au0y
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-urah-tenant/rhtap-demo-app/hacbs-test-project-au0y@sha256:b39e6a34bd3998ff40011e7db960d8e9c58ebc66c24d0b22fa7d66fda1cfe6b8
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
